[build-system]
requires = ["setuptools", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = [
  ".pre-commit-config.yaml",
  "Makefile",
  "tests/*"
]

[tool.setuptools_scm]
version_scheme = 'calver-by-date'
